export const BASE_URL = ''
export const USER_URL = '/api/users'
export const CATEGORY_URL = '/api/category'
export const PRODUCT_URL = '/api/products'
export const UPLOAD_URL = '/api/upload'
export const ORDERS_URL = '/api/orders'
export const paypal_URL = '/api/config/paypal'
